const STORAGE_NAME = '@gameplay'

const USERS_COLLECTION = `${STORAGE_NAME}:users`
const APPOINTMENTS_COLLECTION = `${STORAGE_NAME}:appointments`

export {
  USERS_COLLECTION,
  APPOINTMENTS_COLLECTION
}